// <auto-generated />
namespace GreenToys.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addtotypeoftoydescription1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtotypeoftoydescription1));
        
        string IMigrationMetadata.Id
        {
            get { return "201908071037413_addtotypeoftoydescription1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
